# **Diplomado IA: Aprendizaje Profundo I - Parte 1**. <br> Práctico Clase 7: PyTorch
---
---

**Profesores:**
- Alain Raymond
- Gabriel Sepúlveda
- Miguel Fadic
- Álvaro Soto

**Ayudante:**
- Andrés Villa
---
---

El siguiente práctico se debe realizar de forma individual. El formato de entregar es el **archivo .ipynb con todas las celdas ejecutadas**. Las secciones donde se planteen preguntas de forma explícita, deben ser respondida en celdas de texto, y no se aceptará solo el _output_ de una celda de código como respuesta.

**Nombre alumno:** Vicente Zapata

El siguiente práctico contendrá 1 o más actividades a realizar. Algunas actividades corresponderán a escribir código y otras a responder preguntas.

Antes de responder, se recomienda **fuertemente** revisar las secciones previas donde se desarrollan los ejemplos, dado que algunas de las actividades pueden ser completadas reutilizando el mismo código.


---
**IMPORTANTE:** habrá un bonus de 1 décima para todos aquellos alumnos/as que muestren buen orden en sus respuestas (esto aplica a legibilidad de código, buena redacción, formalidad, organización del jupyter notebook, seguimiento de instrucciones, etc). El criterio lo pondrá cada ayudante corrector. La nota máxima obtenible en el laboratorio es 7.0

## El Tensor: la unidad fundamental.

Los tensores son el elemento fundamental con que trabajarán nuestras redes profundas. Un tensor es simplemente una matriz de n-dimensiones.

* En **imágenes**, usamos tensores de 4 dimensiones: 3 dimensiones (alto, ancho y color) más una cuarta dimensión asociada a los elementos del batch.

* Cuando trabajamos con **texto** podemos tener tensores en 3 dimensiones (dimensión de embedding, palabras y batch).

* Si trabajamos con **videos** tenemos que agregar otra dimensión para el tiempo. En fin, todos estos datos distintos al final se representan como matrices de números en 3, 4 ó 5 dimensiones distintas.

Pytorch representa los tensores via la clase torch.Tensor. Todas las redes neuronales que hagamos requieren tensores para poder trabajar. Nuestros datasets no servirán de nada si no podemos transformarlos en tensores que podamos ocupar con nuestras redes. Si han trabajado con *ndarray* de Numpy la forma de ocuparlos es muy similar. Veamos un tensor de ejemplo de 3 dimensiones: ancho, alto y batch.

In [1]:
import torch

batch_dim = 2
ancho = 4
alto = 3
tensor_ejemplo = torch.randn((batch_dim, ancho, alto)).float() # Tensor aleatorio
print("El tensor es: {}\n".format(tensor_ejemplo))
print("La forma del tensor es: {}".format(tensor_ejemplo.shape))
print("El tipo del tensor es: {}".format(type(tensor_ejemplo)))

El tensor es: tensor([[[ 0.3026, -0.0321, -1.3663],
         [ 1.0971, -0.1890,  1.3987],
         [-1.6124,  1.6450,  0.1099],
         [-0.2167, -1.0247,  0.7508]],

        [[ 1.7864, -0.6580, -0.2605],
         [-1.0101, -0.9766, -1.0085],
         [ 0.9454,  0.7786,  0.0734],
         [ 0.7070, -1.2314, -0.0299]]])

La forma del tensor es: torch.Size([2, 4, 3])
El tipo del tensor es: <class 'torch.Tensor'>


In [2]:
n = (10, 3, 224, 224)

Crear un tensor desde un arreglo de Python es sencillo:

In [3]:
arreglo = [[1, 2, 3], [4, 5, 6]]
tensor_desde_arreglo = torch.tensor(arreglo)
print(tensor_desde_arreglo, tensor_desde_arreglo.shape)
tensor_desde_arreglo2 = torch.tensor(arreglo)
suma = tensor_desde_arreglo +  tensor_desde_arreglo2
print(suma)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


Uno trabaja los tensores de la misma manera que cualquier otra variable numérica en Python. Se pueden, sumar y restar sin problema. La multiplicación por escalares no supone problema y la multiplicación de tensores también está soportada.



In [4]:
tensor_1 = torch.randn((10,2,3))
tensor_2 = torch.randn((10,2,3))

tensor_3 = tensor_1*tensor_2
print(tensor_1.shape)
print(tensor_2)
print(tensor_3)

torch.Size([10, 2, 3])
tensor([[[ 0.3055, -1.6831, -0.7443],
         [ 1.0963,  0.4094,  0.1044]],

        [[-0.7438, -1.1072, -0.5800],
         [ 0.3329, -1.6941,  0.9378]],

        [[-2.8635, -0.0185, -0.4975],
         [-0.7701, -1.6215,  1.1241]],

        [[-0.5429, -0.9452,  0.9357],
         [ 0.8252,  0.9002,  0.9610]],

        [[ 0.2417, -0.4422,  0.5539],
         [ 0.9797,  1.3140,  3.5235]],

        [[-0.0915, -0.5452, -0.1098],
         [ 0.1642, -1.6611,  0.5614]],

        [[ 1.0142,  0.1173,  1.3766],
         [ 0.0937,  0.2621,  0.8840]],

        [[-0.0939,  0.0242,  0.6534],
         [ 0.7693,  0.7336, -0.1214]],

        [[-0.2942,  0.1651, -0.9476],
         [-0.0263, -0.2362, -0.4203]],

        [[ 0.1858,  0.8639,  0.3551],
         [-1.2520,  0.7943, -1.3981]]])
tensor([[[-4.4419e-03, -3.0552e+00,  3.5996e-01],
         [ 1.5033e+00,  3.1382e-01,  1.9553e-01]],

        [[-8.5391e-01, -2.5079e-01,  3.0222e-01],
         [-1.0274e-01, -3.0595e-02, -7.9208e-

Podemos indexarlos:

In [5]:
print(tensor_1.shape)

lista = [1, 2, 3,4]

print(lista[0:2])

tensor_indexado = tensor_1[0:2,0,0]
print(tensor_indexado, tensor_indexado.shape)

torch.Size([10, 2, 3])
[1, 2]
tensor([-0.0145,  1.1481]) torch.Size([2])


In [6]:
torch.randn(10, 3, 64, 64).shape

torch.Size([10, 3, 64, 64])

#### Sobre la dimensión batch

La dimensión de batch es importante pues es la que nos permite poder entrenar de forma paralela en nuestras GPUs. El estándar de Pytorch es que ésta es la primera dimensión de nuestros tensores siempre. Aunque solo evaluar un elemento en nuestra red, este debe tener una dimensión de batch en su primer lugar o sino no funcionará. También es necesario mencionar que Pytorch espera siempre que la dimensión del canal vaya antes que las dimensiones de ancho y alto en imágenes.

### Sobre el dispositivo asociado

Los tensores son procesados por la CPU o por una GPU. Como quizás hemos escuchado antes, sabemos que parte de la explosión de Deep Learning viene por la disponibilidad de GPUs cada vez más poderosas. Para poder trabajar en GPU un tensor tenemos que hacer lo siguiente:

In [7]:
tensor_nuevo = torch.randn((1,2,3))     # Por defecto el tensor está en CPU
tensor_nuevo_gpu = tensor_nuevo.cuda()  # Creé una copia de tensor_nuevo en GPU!
otra_forma = tensor_nuevo.to("cuda")    # Creé otra copia de tensor_nuevo en GPU!
print(otra_forma)


tensor([[[1.7721, 0.5733, 1.3591],
         [0.7325, 0.8520, 0.5018]]], device='cuda:0')


## Definición del Modelo
Como vimos en el laboratorio pasado, definir un modelo de aprendizaje profundo consiste en definir una nueva clase que herede de torch.nn.Module.

Esta clase debe implementar dos métodos para funcionar como un modelo válido en Pytorch:

* Método \_\_init\_\_(self): el constructor de la clase. Aquí es donde usualmente definiremos todos los elementos arquitéctonicos de nuestra red. Aquí definiremos que capas tendrá, qué funciones de activación, funciones de pooling, etc.

* Método forward(self, input): define las conexiones entre capas del modelo, o cómo debe fluir la información que entra en él. Debe retornar un tensor.

### Elementos arquitectónicos

Todos estos elementos están definidos en el paquete torch.nn (de Neural Networks). Todos derivan de la clase torch.nn.Module.

* **Linear:** capa lineal. Toma como parámetros las cantidades de neuronas de entrada y de salida.
* **Conv1d, Conv2d, Conv3d**: capas convolucionales de 1, 2 y 3 dimensiones respectivamente. Definidas por el tamaño del kernel que ocupan, el *stride*, filtros de entrada y de salida.
* **ReLU**: función de activación. No tiene parámetros.
* **Sigmoid**: función de activación. No tiene parámetros.
* **Softmax**: capa que transforma el output en una distribución de probabilidad. Parámetro es sobre la o las dimensiones que se aplica.
* **MaxPool1d, MaxPool2d, MaxPool3d**: Funciones de pooling en 1,2 y 3 dimensiones respectivamente.
* **Dropout**: capa que deja en 0 neuronas con probabilidad $p$. Parámetro: $p$.
* **BatchNorm2d**: capa que normaliza el input de acuerdo a una media y varianza aprendidas.
* **LayerNorm**:
* **Sequential**: es un agrupador de Módulos. Se encarga de que la información fluya de forma secuencial entre los módulos que contiene.

In [8]:
import torch
from torch.nn import Linear, ReLU, Sigmoid, Sequential, Softmax, BatchNorm1d, BatchNorm2d, Dropout, LayerNorm

tensor_prueba = torch.randn((3, 5))

print(tensor_prueba, tensor_prueba.shape)

# Capa Lineal que va de 5 dimensiones a 8
capa_lineal = Linear(5, 8)
tensor_nuevo = capa_lineal(tensor_prueba)
print("Tensor después de Capa Lineal:")
print(tensor_nuevo, tensor_nuevo.shape)

tensor([[ 0.0985,  0.4447,  1.0340,  1.4601,  0.4887],
        [ 0.4574,  1.1052, -1.2233,  1.4103,  0.6834],
        [ 1.2958, -0.1321, -0.9771, -0.7331, -0.0845]]) torch.Size([3, 5])
Tensor después de Capa Lineal:
tensor([[ 1.2489,  0.3931, -0.8846, -0.7542, -0.1782,  0.7956,  0.9579,  0.0572],
        [ 0.3293, -0.2736, -1.2252, -0.3010, -0.4448,  0.6301, -0.0929, -0.9295],
        [-0.4951,  0.0093, -0.0351,  0.1946, -0.5987,  0.3274, -0.8663, -0.5995]],
       grad_fn=<AddmmBackward0>) torch.Size([3, 8])


In [9]:
# Funciones de Activación
# ReLU
relu = ReLU()
print("Antes de ReLU: ")
print(tensor_prueba)
print("Después de ReLU: ")
print(relu(tensor_prueba))

Antes de ReLU: 
tensor([[ 0.0985,  0.4447,  1.0340,  1.4601,  0.4887],
        [ 0.4574,  1.1052, -1.2233,  1.4103,  0.6834],
        [ 1.2958, -0.1321, -0.9771, -0.7331, -0.0845]])
Después de ReLU: 
tensor([[0.0985, 0.4447, 1.0340, 1.4601, 0.4887],
        [0.4574, 1.1052, 0.0000, 1.4103, 0.6834],
        [1.2958, 0.0000, 0.0000, 0.0000, 0.0000]])


In [10]:
# Sigmoid
s = Sigmoid()
print("Antes de Sigmoid: ")
print(tensor_prueba)
print("Después de Sigmoid: ")
print(s(tensor_prueba))

Antes de Sigmoid: 
tensor([[ 0.0985,  0.4447,  1.0340,  1.4601,  0.4887],
        [ 0.4574,  1.1052, -1.2233,  1.4103,  0.6834],
        [ 1.2958, -0.1321, -0.9771, -0.7331, -0.0845]])
Después de Sigmoid: 
tensor([[0.5246, 0.6094, 0.7377, 0.8116, 0.6198],
        [0.6124, 0.7512, 0.2274, 0.8038, 0.6645],
        [0.7851, 0.4670, 0.2735, 0.3245, 0.4789]])


In [11]:
# Softmax
soft = Softmax(dim=0)
print("Antes de Softmax: ")
print(tensor_prueba)
print("Después de Softmax: ")
soft_tensor = soft(tensor_prueba)
print(soft_tensor)
print(soft_tensor.sum(dim=0))

Antes de Softmax: 
tensor([[ 0.0985,  0.4447,  1.0340,  1.4601,  0.4887],
        [ 0.4574,  1.1052, -1.2233,  1.4103,  0.6834],
        [ 1.2958, -0.1321, -0.9771, -0.7331, -0.0845]])
Después de Softmax: 
tensor([[0.1741, 0.2859, 0.8074, 0.4847, 0.3599],
        [0.2493, 0.5535, 0.0845, 0.4612, 0.4373],
        [0.5765, 0.1606, 0.1081, 0.0541, 0.2029]])
tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000])


In [12]:
# Sequential
# Unamos pasos
seq = Sequential(capa_lineal, relu, soft)
tensor_final = seq(tensor_prueba)
print("Aplicando Sequential: ")
print(tensor_final, tensor_final.shape)

Aplicando Sequential: 
tensor([[0.5933, 0.4244, 0.3333, 0.3111, 0.3333, 0.4043, 0.5658, 0.3462],
        [0.2365, 0.2865, 0.3333, 0.3111, 0.3333, 0.3426, 0.2171, 0.3269],
        [0.1702, 0.2891, 0.3333, 0.3779, 0.3333, 0.2531, 0.2171, 0.3269]],
       grad_fn=<SoftmaxBackward0>) torch.Size([3, 8])


In [13]:
# Dropout
drop = Dropout(p=0.9) # con probabilidad de dejar en 0 de 0.5.

tensor_dropout = drop(tensor_prueba)
print(tensor_dropout)

tensor([[0.0000, 4.4474, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, -0.0000, 0.0000, 0.0000],
        [0.0000, -0.0000, -0.0000, -0.0000, -0.0000]])


In [14]:
# Batch Normalization 1d
tensor_lineal = 100*torch.randn((3, 5))  # Una imagen con varianza alta
bn = BatchNorm1d(5, momentum=None)
print("La media de los vectores originales por dimensión es: {}".format(tensor_lineal.mean(dim=[0])))
print("La varianza de los vectores originales por dimensión es: {}".format(tensor_lineal.var(dim=[0], unbiased=False)))
print("Las medias por dimensión de BN inicialmente son: {}".format(bn.running_mean))
print("Las varianzas por dimensión de BN inicialmente son: {}".format(bn.running_var))

tensor_bn = bn(tensor_lineal)

print("La media por dimensión del resultado es: {}".format(tensor_bn.mean(dim=[0])))
print("La varianza por dimensión del resultado es: {}".format(tensor_bn.var(dim=[0], unbiased=False)))
print("Las medias por dimensión de BN ahora son: {}".format(bn.running_mean))
print("Las varianzas por dimensión de BN ahora son: {}".format(bn.running_var))

for n, p in bn.named_parameters():
    print(n,p)

La media de los vectores originales por dimensión es: tensor([-53.7051, -23.5546, 116.1344,  59.6115,   0.5886])
La varianza de los vectores originales por dimensión es: tensor([1231.3066, 2728.6565,  970.6059,  916.1448,  799.3021])
Las medias por dimensión de BN inicialmente son: tensor([0., 0., 0., 0., 0.])
Las varianzas por dimensión de BN inicialmente son: tensor([1., 1., 1., 1., 1.])
La media por dimensión del resultado es: tensor([ 0.0000e+00,  0.0000e+00, -2.3842e-07,  7.9473e-08,  0.0000e+00],
       grad_fn=<MeanBackward1>)
La varianza por dimensión del resultado es: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<VarBackward0>)
Las medias por dimensión de BN ahora son: tensor([-53.7051, -23.5546, 116.1344,  59.6115,   0.5886])
Las varianzas por dimensión de BN ahora son: tensor([1846.9600, 4092.9846, 1455.9088, 1374.2173, 1198.9531])
weight Parameter containing:
tensor([1., 1., 1., 1., 1.], requires_grad=True)
bias Parameter containing:
tensor([0., 0., 0., 0., 0.],

In [15]:
# Batch Normalization 2d
tensor_imagenes = 20*torch.randn((4, 3, 2, 2))  # Una imagen con varianza alta
bn = BatchNorm2d(3, momentum = None, eps=0.0)                             # 3 es el número de canales


print("La media de las imágenes originales por canal es: {}".format(tensor_imagenes.mean(dim=[0,2,3])))
print("La varianza de las imágenes originales por canal es: {}".format(tensor_imagenes.var(dim=[0,2,3], unbiased=True)))
print("Las medias por canal de BN inicialmente son: {}".format(bn.running_mean))
print("Las varianzas por canal de BN inicialmente son: {}".format(bn.running_var))

tensor_bn = bn(tensor_imagenes)
print("La media por canal es: {}".format(tensor_bn.mean(dim=[0,2,3])))
print("La varianza por canal es: {}".format(tensor_bn.var(dim=[0,2,3], unbiased=True)))
print("Las medias por canal de BN ahora son: {}".format(bn.running_mean))
print("Las varianzas por canal de BN ahora son: {}".format(bn.running_var))

for n, p in bn.named_parameters():
    print(n,p)

La media de las imágenes originales por canal es: tensor([-2.7662, -8.2440,  1.1364])
La varianza de las imágenes originales por canal es: tensor([453.9541, 365.1471, 511.3632])
Las medias por canal de BN inicialmente son: tensor([0., 0., 0.])
Las varianzas por canal de BN inicialmente son: tensor([1., 1., 1.])
La media por canal es: tensor([2.9802e-08, 7.4506e-09, 0.0000e+00], grad_fn=<MeanBackward1>)
La varianza por canal es: tensor([1.0667, 1.0667, 1.0667], grad_fn=<VarBackward0>)
Las medias por canal de BN ahora son: tensor([-2.7662, -8.2440,  1.1364])
Las varianzas por canal de BN ahora son: tensor([453.9541, 365.1470, 511.3632])
weight Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
bias Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [16]:
# Layer Normalization
tensor_lineal = 100*torch.randn((20, 100))  # Una imagen con varianza alta
ln = LayerNorm(100, eps=0 ,elementwise_affine=True) # elementwise_affine determina si tiene parámetros aprendibles o no.
print("Media del resultado: ", ln(tensor_lineal).mean(dim=1))
print("Desviación estándar del resultado: ", ln(tensor_lineal).std(dim=1, unbiased=False))
for n, p in ln.named_parameters():
  print(n,p)

# Cambiemos la media y desviación estándar a mano
new_weight1 = torch.ones(100) * 100.0
new_weight2 = torch.ones(100) * 5.0
with torch.no_grad():
    ln.weight.copy_(new_weight1)
    ln.bias.copy_(new_weight2)

# evaluamos de nuevo sobre los mismos datos
print("Media del resultado: ", ln(tensor_lineal).mean(dim=1))
print("Desviación estándar del resultado: ", ln(tensor_lineal).std(dim=1, unbiased=False))

Media del resultado:  tensor([-4.5300e-08,  2.3842e-08,  0.0000e+00, -7.1526e-09, -2.3842e-09,
         2.8610e-08,  2.3842e-08,  2.3842e-09,  1.4305e-08,  0.0000e+00,
        -2.0266e-08,  8.3447e-09,  4.7684e-09, -1.9073e-08, -2.3842e-09,
        -2.3842e-08,  0.0000e+00, -4.7684e-09,  1.4305e-08,  9.5367e-09],
       grad_fn=<MeanBackward1>)
Desviación estándar del resultado:  tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000], grad_fn=<StdBackward0>)
weight Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

### Revisitando AlexNet

In [17]:
import torch
import torch.nn as nn           # Esto es PyTorch y su módulo de Redes Neuronales

class MiAlexNet(nn.Module):               # Esta clase representa nuestro modelo

    def __init__(self):   # Constructor, aquí armamos las piezas de nuestra red
        super(MiAlexNet, self).__init__()
        # Bloques Convolucionales
        # Recordemos que los Bloques Convolucionales van a estar hechos de 3
        # elementos: Convolución, Pooling y Activación.
        # En este caso usaremos Convoluciones 2d, Max Pooling y ReLU


        # Input = 3x 224 x 224 Output = 96 x 55 x 55 --> Max Pool = 96 x 27 x 27
        self.conv1 = nn.Sequential(
            nn.Conv2d(                           # Todo esto define a la Convolución
                      in_channels=3,             # Filtros/Canales de Entrada (RGB)
                      out_channels=96,           # Filtros/Canales de Salida
                      kernel_size=(11,11),       # Tamaño de la Convolución
                      stride=(4,4),              # Stride
                      padding=2),                # Cuántos pixeles de padding
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)), # Max Pooling
            nn.ReLU()                            # Activación
        )

        # Input = 96 x 27 x 27 Output = 256 x 27 x 27 --> Max Pool = 256 x 13 x 13
        self.conv2 = nn.Sequential(
            nn.Conv2d(
                      in_channels=96,
                      out_channels=256,
                      kernel_size=(5,5),
                      stride=(1,1),
                      padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        # Input = 256 x 13 x 13 Output = 384 x 13 x 13
        self.conv3 = nn.Sequential(
            nn.Conv2d(
                      in_channels=256,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 384 x 13 x 13
        self.conv4 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 256 x 13 x 13 --> MaxPool = 256 x 6 x 6
        self.conv5 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=256,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        ##
        self.flat = nn.Flatten()    # Capa aplanamiento para poder vincular
                                    # resultado convolucional con capas
                                    # lineales.

        # Bloques Fully Connected/MLP
        # Input = 256 x 6 x 6 = 9216 Output = 4096
        self.fc6 = nn.Sequential( #nn.Dropout(),
                                  nn.Linear(9216, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 4096
        self.fc7 = nn.Sequential(  #nn.Dropout(),
                                  nn.Linear(4096, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 1000
        self.fc8 = nn.Sequential(
                                  nn.Linear(4096, 102)
                                  )



    def forward(self, x):        # Aquí armamos cómo se conectan las piezas
                                 # Esta red es sencilla pues solo tenemos
                                 # que conectar las piezas una detrás de la
                                 # otra. No todas las redes son así.
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)

        return x

In [18]:
m = MiAlexNet()

In [19]:
for n, p in m.named_parameters():
  print(n, p.shape)


conv1.0.weight torch.Size([96, 3, 11, 11])
conv1.0.bias torch.Size([96])
conv2.0.weight torch.Size([256, 96, 5, 5])
conv2.0.bias torch.Size([256])
conv3.0.weight torch.Size([384, 256, 3, 3])
conv3.0.bias torch.Size([384])
conv4.0.weight torch.Size([384, 384, 3, 3])
conv4.0.bias torch.Size([384])
conv5.0.weight torch.Size([256, 384, 3, 3])
conv5.0.bias torch.Size([256])
fc6.0.weight torch.Size([4096, 9216])
fc6.0.bias torch.Size([4096])
fc7.0.weight torch.Size([4096, 4096])
fc7.0.bias torch.Size([4096])
fc8.0.weight torch.Size([102, 4096])
fc8.0.bias torch.Size([102])


In [20]:
fotos_de_mentira = torch.randn(15, 3, 224, 224)

m(fotos_de_mentira).shape

torch.Size([15, 102])

## Manejo de Datos

En un problema normal de Machine Learning, usualmente la gestión de datos no era muy importante dado que los datasets en general son pequeños. Sin embargo, dados los volúmenes de datos que requieren los modelos de aprendizaje profundo, se vuelve difícil mantener los datos en memoria. Por esto, se requiere consumirlos de manera parcelada para poder ocuparlos con las restricciones de hardware que tenemos.

Pytorch resuelve el problema mediante dos abstracciones: las clases *Dataset* y *DataLoader*.

* La clase *Dataset* trabaja como una interfaz sencilla para acceder nuestros datos físicos.
* La clase *DataLoader* se encarga de agrupar los elementos de la clase *Dataset* en *batches* para pasarle a nuestro modelo.

Usualmente, el mayor trabajo reside en definir una clase Dataset apropiada para nuestro conjunto de datos. Por suerte, si queremos trabajar con ciertos conjuntos de datos estándar, Pytorch ya tiene definido estos datasets por nosotros.

Si no, lo único que tenemos que hacer es definir una clase que herede de torch.utils.data.Dataset y que implemente dos métodos:

* \_\_len(self)\_\_: método que devuelva el tamaño total del dataset.
* \_\_getitem\_\_(self, index): método que entregue un elemento particular del dataset dado un índice (index).

### Usar Datasets predefinidos

In [21]:
from torchvision.datasets import MNIST, CIFAR10

mnist_train = MNIST(root=".", train=True, download=True)
cifar = CIFAR10(root=".", train=True, download=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 20.3MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 496kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.57MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 5.86MB/s]
100%|██████████| 170M/170M [00:03<00:00, 43.1MB/s]


In [22]:
len(mnist_train)

60000

Veamos un ejemplo del dataset.

In [23]:
mnist_train[459]

(<PIL.Image.Image image mode=L size=28x28>, 3)

Vemos que contiene dos elementos: el primero es una imagen en formato PIL y el segundo es la clase asociada a esa imagen (nuestro target o ground truth). La imagen se ve así:

In [24]:
from IPython.display import display     # Esto no es Pytorch, es solo una librería
                                        # para desplegar imágenes en Colab.
display(mnist_train[459][0])
#display(cifar[0][0])

Sin embargo, una imagen en formato PIL no es un tensor de Pytorch. Tenemos que hacer algo para transformarla! Por suerte para nosotros, Pytorch nos ofrece transformaciones estándar para imágenes, en particular, una para transformar imágenes PIL a tensores. Veamos cómo:

In [25]:
from torchvision.transforms import ToTensor
mnist_train = MNIST(root=".", train=True, download=True, transform=ToTensor())

In [26]:
mnist_train[459]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

Ahora nuestro Dataset automáticamente transforma las imágenes PIL a tensores de Pytorch!

### Crear un Dataset de ejemplo

Vamos a crear un Dataset para el conjunto de datos Flowers que vimos el laboratorio pasado.

In [27]:
!wget https://www.dropbox.com/s/q53g4cmpnvzhnhi/flowers.tar.gz -q --show-progress
!tar -xzf flowers.tar.gz

flowers.tar.gz      100%[===================>] 328.99M  17.4MB/s    in 20s     


In [28]:
from os import listdir
from os.path import join
from PIL import Image
import torch
from torchvision.transforms import Compose, ToTensor, Resize
class Flowers(torch.utils.data.Dataset):
    def __init__(self, root, transform=None):
        self.root = root
        self.transform = transform
        self.imagenes = []       # Vincula el indice con un nombre de archivo
        self.imgs_to_class = []  # Vincula el indice con una clase
        self.imagenes, self.imgs_to_class = self.armar_indices(root)

    def armar_indices(self, root):
        n_classes = len(listdir(root)) # El número de carpetas es la cantidad de clases
        contador = 0
        lista_imagenes = []
        imgs_to_class = []
        for clase in listdir(root):
            directorio = join(root, clase)
            for archivo in listdir(directorio):
                lista_imagenes.append(archivo)
                contador+=1
                imgs_to_class.append(int(clase))

        return lista_imagenes, imgs_to_class

    def obtener_imagen(self, archivo):

        im = Image.open(archivo)
        return im

    def __getitem__(self, idx):

        nombre_archivo = self.imagenes[idx]
        clase = self.imgs_to_class[idx]
        ruta_img = join(self.root, str(clase))
        ruta_img = join(ruta_img, nombre_archivo)
        img = self.obtener_imagen(ruta_img)

        if self.transform is not None:
            img = self.transform(img)
        return img, clase

    def __len__(self):
        return len(self.imagenes)

In [29]:
transforms = Compose([Resize((224,224)), ToTensor()])
f = Flowers('flowers_dataset/train', transform=transforms)
print(f[0])

(tensor([[[0.3922, 0.3922, 0.3882,  ..., 0.3843, 0.4314, 0.4667],
         [0.3843, 0.3843, 0.3804,  ..., 0.3922, 0.4157, 0.4667],
         [0.3725, 0.3725, 0.3725,  ..., 0.3961, 0.4039, 0.4471],
         ...,
         [0.3569, 0.3490, 0.3373,  ..., 0.0863, 0.0863, 0.0863],
         [0.3412, 0.3333, 0.3255,  ..., 0.0902, 0.0863, 0.0863],
         [0.3294, 0.3255, 0.3098,  ..., 0.0902, 0.0863, 0.0863]],

        [[0.4549, 0.4549, 0.4510,  ..., 0.0902, 0.0706, 0.1020],
         [0.4471, 0.4471, 0.4431,  ..., 0.1059, 0.0667, 0.0980],
         [0.4353, 0.4353, 0.4353,  ..., 0.1255, 0.0706, 0.0863],
         ...,
         [0.4000, 0.3922, 0.3804,  ..., 0.0902, 0.0902, 0.0902],
         [0.3843, 0.3765, 0.3647,  ..., 0.0941, 0.0902, 0.0902],
         [0.3725, 0.3647, 0.3490,  ..., 0.0941, 0.0902, 0.0902]],

        [[0.1059, 0.1059, 0.1098,  ..., 0.0667, 0.0667, 0.0745],
         [0.0980, 0.0980, 0.1059,  ..., 0.0745, 0.0510, 0.0863],
         [0.0863, 0.0902, 0.1020,  ..., 0.0863, 0.0353, 0

In [30]:
len(f)

5687

### Iterar sobre los datos

Dado un Dataset, sea hecho por nosotros o uno predefinido, iterar sobre los datos es muy sencillo. Simplemente tenemos que crear un objeto DataLoader que toma como argumento el Dataset y definir el batch size con que queremos trabajar.


Este código iterará por todos los batches de ejemplos de nuestro dataset y parará cuando se acaben. Es decir, esto corre por una **época**.

In [31]:
from torch.utils.data import DataLoader
train_dl = DataLoader(f, batch_size=128, shuffle=True)

for n_batch, (x, target) in enumerate(train_dl):
    print("\rN_Batch: {} input: {}- Label:{}".format(n_batch, x.shape, target.shape), end="")

N_Batch: 44 input: torch.Size([55, 3, 224, 224])- Label:torch.Size([55])

### Optimización

¿Como obtenemos los pesos óptimos para nuestra red? Si recordamos nuestras clases anteriores debemos optimizar la función de pérdida para tratar de encontrar los parámetros de nuestra red que minimizan su valor.

Primero debemos definir la función de pérdida. Éstas están definidas en torch.nn también. Las usuales son:

* CrossEntropyLoss: Entropía Cruzada, mide la distancia entre dos distribuciones de probabilidad. La función de pérdida más común para problemas de clasificación.
* MSELoss: Error cuadrático medio. Pérdida usual en problemas de regresión.

Hay más para revisar en la documentación de Pytorch (https://pytorch.org/docs/stable/nn.html).

Dado el resultado de nuestra red y el ground truth que deberíamos predecir, la pérdida es:


In [38]:
from torch.nn import CrossEntropyLoss
funcion_perdida = CrossEntropyLoss()

In [33]:
loss = funcion_perdida(output, target) # No correr este código, va a dar error! Es un ejemplo!

NameError: name 'output' is not defined

Súper, tenemos la pérdida, ¿cómo calculamos los gradientes?

Para eso necesitamos un algoritmo de optimización. En el curso de Herramientas verán los algoritmos en detalle, pero les debería sonar Stochastic Gradient Descent (SGD), que es el algoritmo estándar de optimización. Este ya está implementado por el paquete torch.optim.


In [39]:
from torch.optim import SGD, Adam

optimizer = SGD(model.parameters())     # Vinculamos el recién creado optimizador
                                        # a los parámetros de nuestro modelo

NameError: name 'model' is not defined

Esto por sí solo todavía no hace nada. El optimizador va a ir gestionando los gradientes que le llegan a cada parámetro de nuestro modelo. Actualizará los valores de los parámetros de acuerdo al algoritmo de optimización que implemente.

Pero para gestionar gradientes tiene que sacarlos de alguna parte. ¡Esto lo hace backpropagation! Por suerte es muy fácil calcularlos en Pytorch.

In [40]:
loss.backward()                         # ¡Backpropagation! Eso es todo.

NameError: name 'loss' is not defined

Luego uniendo todas las piezas, en cada iteración de nuestro algoritmo de entrenamiento haremos lo siguiente:

In [41]:
optimizer.zero_grad()                   # 1. Hacemos cero los gradientes de los parámetros
output = model(input)                   # 2. Propagamos los datos de entrada por nuestro modelo
loss = funcion_perdida(output, target)  # 3. Cálculamos la pérdida
loss.backward()                         # 4. ¡Backpropagation! Calculamos los gradientes
                                        # para nuestros parámetros. ¡Los gradientes
                                        # dejan de ser 0!
optimizer.step()                        # 5. Actualizamos los parámetros de nuestro modelo

NameError: name 'optimizer' is not defined

## Evaluación de Rendimiento

¿Cómo evaluamos el rendimiento? En problemas de clasificación lo que usualmente haremos es comparar el ground truth respecto a lo que predecimos. ¿Qué es lo que predecimos? Usualmente será la clase de mayor valor en su salida entre las N clases que tenemos que predecir. Esto lo podemos hacer usando la función *argmax* de Pytorch.

In [42]:
output = model(input)                       # Tensor de salida de tamaño (batch_size, n_clases)
preds = output.argmax(dim=1)                # Nos quedamos con el índice que tiene mayor valor
                                            # entre las N clases.
n_correctas = (preds == targets).sum()      # preds == targets entrega un tensor de 1s o 0s.
total = targets.shape[0]                    # Total de ejemplos
acc = n_correctas/total                     # Accuracy es correctas/total

NameError: name 'model' is not defined

## Uniendo todo

Vamos a unir todos estos componentes para armar un flujo de entrenamiento completo:

In [43]:
import torch
import torch.nn as nn           # Esto es PyTorch y su módulo de Redes Neuronales

class MiAlexNet(nn.Module):               # Esta clase representa nuestro modelo

    def __init__(self):   # Constructor, aquí armamos las piezas de nuestra red
        super(MiAlexNet, self).__init__()
        # Bloques Convolucionales
        # Recordemos que los Bloques Convolucionales van a estar hechos de 3
        # elementos: Convolución, Pooling y Activación.
        # En este caso usaremos Convoluciones 2d, Max Pooling y ReLU


        # Input = 3x 224 x 224 Output = 96 x 55 x 55 --> Max Pool = 96 x 27 x 27
        self.conv1 = nn.Sequential(
            nn.Conv2d(                           # Todo esto define a la Convolución
                      in_channels=3,             # Filtros/Canales de Entrada (RGB)
                      out_channels=96,           # Filtros/Canales de Salida
                      kernel_size=(11,11),       # Tamaño de la Convolución
                      stride=(4,4),              # Stride
                      padding=2),                # Cuántos pixeles de padding
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)), # Max Pooling
            nn.ReLU()                            # Activación
        )

        # Input = 96 x 27 x 27 Output = 256 x 27 x 27 --> Max Pool = 256 x 13 x 13
        self.conv2 = nn.Sequential(
            nn.Conv2d(
                      in_channels=96,
                      out_channels=256,
                      kernel_size=(5,5),
                      stride=(1,1),
                      padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        # Input = 256 x 13 x 13 Output = 384 x 13 x 13
        self.conv3 = nn.Sequential(
            nn.Conv2d(
                      in_channels=256,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 384 x 13 x 13
        self.conv4 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 256 x 13 x 13 --> MaxPool = 256 x 6 x 6
        self.conv5 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=256,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        ##
        self.flat = nn.Flatten()    # Capa aplanamiento para poder vincular
                                    # resultado convolucional con capas
                                    # lineales.

        # Bloques Fully Connected/MLP
        # Input = 256 x 6 x 6 = 9216 Output = 4096
        self.fc6 = nn.Sequential( #nn.Dropout(),
                                  nn.Linear(9216, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 4096
        self.fc7 = nn.Sequential(  #nn.Dropout(),
                                  nn.Linear(4096, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 1000
        self.fc8 = nn.Sequential(
                                  nn.Linear(4096, 102)
                                  )


    def forward(self, x):        # Aquí armamos cómo se conectan las piezas
                                 # Esta red es sencilla pues solo tenemos
                                 # que conectar las piezas una detrás de la
                                 # otra. No todas las redes son así.
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)

        return x

In [44]:
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.models import alexnet

model = MiAlexNet()
#Descomentar esto para ocupar modelo preentrenado
#model = alexnet(pretrained=True)
#model.features.requires_grad_(False)
#model.classifier = nn.Sequential(
#            nn.Dropout(),
#            nn.Linear(256 * 6 * 6, 4096),
#            nn.ReLU(inplace=True),
#            nn.Dropout(),
#            nn.Linear(4096, 4096),
#            nn.ReLU(inplace=True),
#            nn.Linear(4096, 102),
#        )

model = model.cuda()    # Lo enviamos para que se ejecute en GPU
transforms = Compose([Resize((224, 224)), ToTensor()])
ds_train = Flowers("flowers_dataset/train", transform=transforms) # Creamos

n_epochs = 10
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)

optimizer = Adam(model.parameters(), lr=0.001)    # Creamos nuestro optimizador
loss_function = CrossEntropyLoss()      # Creamos la función de pérdida


model.train()                           # Dejamos el modelo en modo de entrenamiento
for epoch in range(1, n_epochs + 1):
    total_correctas = 0.0
    total_muestras = 0.0

    for x, target in train_dl:          # Iteramos sobre nuestros datos
        # Inicio de la iteración
        optimizer.zero_grad()           # Hacemos cero los gradientes de nuestros parámetros
        x = x.cuda()
        target = target.cuda()          # Enviamos nuestros datos a GPU
        output = model(x)               # Hacemos el forward de nuestros datos

        loss = loss_function(output, target)     # Calculamos la pérdida
        loss.backward()                          # Backpropagation
        optimizer.step()                         # Actualizamos parámetros

        preds = output.argmax(dim=1)             # El máximo valor es nuestra predicción
        correctas = (preds == target).sum()      # Acumulamos las correctas durante la época
        total_correctas += correctas
        total_muestras += target.shape[0]        # Sumamos el tamaño del batch

        accuracy = total_correctas/total_muestras # Acc = correctas/total

        print("\rEpoca {}: Loss: {:.2f} Correctas: {} Total: {} Accuracy: {:.2f}%".format(epoch,
                                                                                      loss,
                                                                                      total_correctas,
                                                                                      total_muestras,
                                                                                      100*accuracy), end="")
    print("")

Epoca 1: Loss: 4.56 Correctas: 153.0 Total: 5687.0 Accuracy: 2.69%
Epoca 2: Loss: 4.25 Correctas: 222.0 Total: 5687.0 Accuracy: 3.90%
Epoca 3: Loss: 3.97 Correctas: 340.0 Total: 5687.0 Accuracy: 5.98%
Epoca 4: Loss: 3.62 Correctas: 452.0 Total: 5687.0 Accuracy: 7.95%
Epoca 5: Loss: 3.88 Correctas: 567.0 Total: 5687.0 Accuracy: 9.97%
Epoca 6: Loss: 3.55 Correctas: 712.0 Total: 5687.0 Accuracy: 12.52%
Epoca 7: Loss: 3.51 Correctas: 840.0 Total: 5687.0 Accuracy: 14.77%
Epoca 8: Loss: 3.14 Correctas: 1038.0 Total: 5687.0 Accuracy: 18.25%
Epoca 9: Loss: 3.08 Correctas: 1180.0 Total: 5687.0 Accuracy: 20.75%
Epoca 10: Loss: 2.91 Correctas: 1410.0 Total: 5687.0 Accuracy: 24.79%


### Evaluando el modelo en el conjunto de Test

In [45]:
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.models import alexnet
ds_test = Flowers("flowers_dataset/test", transform=transforms)
test_dl = DataLoader(ds_test, batch_size=1024)

total_correctas = 0.0
total_muestras = 0.0

model.eval()
for x, target in test_dl:          # Iteramos sobre nuestros datos
    # Inicio de la iteración
                      # Dejamos el modelo en modo evaluación
    with torch.no_grad():               # No se calculará información de gradientes
                                        # en el código de más abajo.
        x = x.cuda()
        target = target.cuda()          # Enviamos nuestros datos a GPU
        output = model(x)               # Hacemos el forward de nuestros datos

        loss = loss_function(output, target)     # Calculamos la pérdida

        preds = output.argmax(dim=1)             # El máximo valor es nuestra predicción
        correctas = (preds == target).sum()      # Acumulamos las correctas durante la época
        total_correctas += correctas
        total_muestras += target.shape[0]        # Sumamos el tamaño del batch

        accuracy = total_correctas/total_muestras # Acc = correctas/total

        print("\rLoss: {:.2f} Correctas: {} Total: {} Accuracy: {:.2f}%".format(loss,
                                                                                total_correctas,
                                                                                total_muestras,
                                                                                100*accuracy), end="")

Loss: 2.98 Correctas: 384.0 Total: 1738.0 Accuracy: 22.09%

## Guardar el Modelo

Una vez entrenado, querremos guardar el modelo para no tener que reentrenarlo cada vez que lo queramos usar. Esto es fácil de hacer en Pytorch.

La forma más eficiente y correcta es simplemente guardar los pesos. Estos se encuentran en una estructura llamada *'state_dict'* en el modelo. Una vez guardados, para recuperar nuestro modelo, tenemos que crear un modelo nuevo y ocupar el método *'load_state_dict'* para cargar los pesos.

In [46]:
torch.save(model.state_dict(), "MNIST/pesos_modelo_entrenado.pth") # Guardamos a disco los pesos

modelo = MiAlexNet()                                # Modelo con pesos aleatorios
pesos = torch.load("MNIST/pesos_modelo_entrenado.pth") # Cargamos los pesos a una variable
modelo.load_state_dict(pesos)                       # ¡Los pesos se encuentran
                                                    # cargados en el modelo!

<All keys matched successfully>

## Actividades

1. Entrene el modelo MiAlexNet por 10 épocas. ¿Qué resultados obtiene en train y test?
2. Modifique el modelo MiAlexNet para que haya una capa de Dropout antes de FC6 y FC7. Entrénelo por 10 épocas. ¿Ve cambios en el rendimiento del modelo?
3. Agregue capas de Batch Normalization (*BatchNorm2d*) antes de Conv3, Conv4 y Conv5. Entrene el modelo por 10 épocas. ¿Ve algún cambio en el entrenamiento?
4. Ocupe el modelo preentrenado en ImageNet de AlexNet. Entrénelo por 10 épocas. ¿Afecta en algo en rendimiento? Para ocupar el modelo preentrenado reemplace esta línea del código de entrenamiento:

In [47]:
model = MiAlexNet()     # Creamos el modelo

Por estas otras líneas:

In [48]:
from torchvision.models import alexnet

model = alexnet(pretrained=True)
model.features.requires_grad_(False)
model.classifier = nn.Sequential(
            nn.Dropout(),
            nn.Linear(256 * 6 * 6, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
            nn.Linear(4096, 102),
        )

/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Downloading: "https://download.pytorch.org/models/alexnet-owt-7be5be79.pth" to /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth


100%|██████████| 233M/233M [00:01<00:00, 198MB/s]


### Respuestas Actividad

Por favor, sus respuestas a la actividad acá. No modificar el código anterior.

**Actividad 1**

In [49]:
# ACTIVIDAD 1: Entrenar MiAlexNet por 10 épocas
# =============================================
# Vamos a entrenar el modelo básico sin modificaciones

# Importamos las librerías necesarias
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
import torch

# Creamos el modelo original (sin cambios)
model_act1 = MiAlexNet()
model_act1 = model_act1.cuda()  # Lo enviamos a la GPU para que sea más rápido

# Preparamos los datos
# Transforms es para redimensionar las imágenes a 224x224
transforms = Compose([Resize((224, 224)), ToTensor()])
ds_train = Flowers("flowers_dataset/train", transform=transforms)
ds_test = Flowers("flowers_dataset/test", transform=transforms)

# DataLoader nos ayuda a cargar los datos en grupos (batches)
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)
test_dl = DataLoader(ds_test, batch_size=128)

# Configuramos el entrenamiento
n_epochs = 10  # Número de veces que veremos todos los datos
optimizer = Adam(model_act1.parameters(), lr=0.001)  # Optimizador para ajustar los pesos
loss_function = CrossEntropyLoss()  # Función para medir qué tan mal lo hace el modelo

# ===== ENTRENAMIENTO =====
print("Entrenando modelo MiAlexNet original por 10 épocas...")
print("="*60)

model_act1.train()  # Ponemos el modelo en modo entrenamiento
for epoch in range(1, n_epochs + 1):
    total_correctas = 0.0
    total_muestras = 0.0

    for x, target in train_dl:  # Recorremos los datos de entrenamiento
        # Enviamos los datos a la GPU
        x = x.cuda()
        target = target.cuda()

        # Pasamos los datos por el modelo (forward)
        output = model_act1(x)

        # Calculamos el error
        loss = loss_function(output, target)

        # Ajustamos los pesos del modelo (esto es el aprendizaje)
        optimizer.zero_grad()  # Limpiamos los gradientes anteriores
        loss.backward()  # Calculamos los nuevos gradientes
        optimizer.step()  # Actualizamos los pesos

        # Calculamos cuántas predicciones fueron correctas
        preds = output.argmax(dim=1)  # La clase con mayor probabilidad
        correctas = (preds == target).sum()
        total_correctas += correctas
        total_muestras += target.shape[0]

    # Al final de cada época, mostramos el progreso
    accuracy_train = total_correctas / total_muestras
    print(f"Época {epoch}/{n_epochs} - Train Accuracy: {100*accuracy_train:.2f}%")

print("\\n" + "="*60)
print("¡Entrenamiento completado!")
print("="*60)

# ===== EVALUACIÓN EN TEST =====
print("\\nEvaluando en conjunto de TEST...")
model_act1.eval()  # Ponemos el modelo en modo evaluación
total_correctas_test = 0.0
total_muestras_test = 0.0

with torch.no_grad():  # No necesitamos calcular gradientes para evaluar
    for x, target in test_dl:
        x = x.cuda()
        target = target.cuda()
        output = model_act1(x)

        preds = output.argmax(dim=1)
        correctas = (preds == target).sum()
        total_correctas_test += correctas
        total_muestras_test += target.shape[0]

accuracy_test = total_correctas_test / total_muestras_test
print(f"Test Accuracy: {100*accuracy_test:.2f}%")

# RESPUESTA:
print("\\n" + "="*60)
print("RESULTADOS ACTIVIDAD 1:")
print("="*60)
print(f"Train Accuracy final: {100*accuracy_train:.2f}%")
print(f"Test Accuracy: {100*accuracy_test:.2f}%")
print("\\nExplicación:")
print("El modelo aprende a clasificar las flores, pero puede tener overfitting")
print("(aprende muy bien los datos de entrenamiento pero no generaliza bien)")
print("si la diferencia entre train y test es muy grande.")
print("="*60)

Entrenando modelo MiAlexNet original por 10 épocas...
Época 1/10 - Train Accuracy: 2.36%
Época 2/10 - Train Accuracy: 3.02%
Época 3/10 - Train Accuracy: 4.50%
Época 4/10 - Train Accuracy: 6.98%
Época 5/10 - Train Accuracy: 10.20%
Época 6/10 - Train Accuracy: 12.36%
Época 7/10 - Train Accuracy: 16.25%
Época 8/10 - Train Accuracy: 19.24%
Época 9/10 - Train Accuracy: 23.03%
Época 10/10 - Train Accuracy: 27.24%
\n============================================================
¡Entrenamiento completado!
\nEvaluando en conjunto de TEST...
Test Accuracy: 27.39%
\n============================================================
RESULTADOS ACTIVIDAD 1:
Train Accuracy final: 27.24%
Test Accuracy: 27.39%
\nExplicación:
El modelo aprende a clasificar las flores, pero puede tener overfitting
(aprende muy bien los datos de entrenamiento pero no generaliza bien)
si la diferencia entre train y test es muy grande.


**Actividad 2**

In [50]:
# ACTIVIDAD 2: Agregar Dropout antes de FC6 y FC7
# ===================================================
# Dropout ayuda a prevenir el overfitting (sobreajuste)
# Apaga aleatoriamente algunas neuronas durante el entrenamiento

# Creamos una nueva versión del modelo CON Dropout
class MiAlexNetConDropout(nn.Module):
    def __init__(self):
        super(MiAlexNetConDropout, self).__init__()

        # Las capas convolucionales son iguales
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=96, kernel_size=(11,11), stride=(4,4), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(in_channels=96, out_channels=256, kernel_size=(5,5), stride=(1,1), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        self.conv3 = nn.Sequential(
            nn.Conv2d(in_channels=256, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )
        self.conv4 = nn.Sequential(
            nn.Conv2d(in_channels=384, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )
        self.conv5 = nn.Sequential(
            nn.Conv2d(in_channels=384, out_channels=256, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )

        self.flat = nn.Flatten()

        # AQUÍ ESTÁ EL CAMBIO: Agregamos Dropout antes de FC6 y FC7
        # Dropout(0.5) significa que apagará el 50% de las neuronas aleatoriamente
        self.fc6 = nn.Sequential(
            nn.Dropout(0.5),  # ← NUEVO: Dropout antes de FC6
            nn.Linear(9216, 4096),
            nn.ReLU()
        )
        self.fc7 = nn.Sequential(
            nn.Dropout(0.5),  # ← NUEVO: Dropout antes de FC7
            nn.Linear(4096, 4096),
            nn.ReLU()
        )
        self.fc8 = nn.Sequential(
            nn.Linear(4096, 102)
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)
        return x

# Creamos y entrenamos el nuevo modelo
model_act2 = MiAlexNetConDropout()
model_act2 = model_act2.cuda()

# Preparamos los datos (igual que antes)
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)
test_dl = DataLoader(ds_test, batch_size=128)

n_epochs = 10
optimizer = Adam(model_act2.parameters(), lr=0.001)
loss_function = CrossEntropyLoss()

# ===== ENTRENAMIENTO CON DROPOUT =====
print("Entrenando modelo CON Dropout por 10 épocas...")
print("="*60)

model_act2.train()
for epoch in range(1, n_epochs + 1):
    total_correctas = 0.0
    total_muestras = 0.0

    for x, target in train_dl:
        x = x.cuda()
        target = target.cuda()
        output = model_act2(x)
        loss = loss_function(output, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        preds = output.argmax(dim=1)
        correctas = (preds == target).sum()
        total_correctas += correctas
        total_muestras += target.shape[0]

    accuracy_train = total_correctas / total_muestras
    print(f"Época {epoch}/{n_epochs} - Train Accuracy: {100*accuracy_train:.2f}%")

print("\\n" + "="*60)
print("¡Entrenamiento completado!")
print("="*60)

# ===== EVALUACIÓN EN TEST =====
print("\\nEvaluando en conjunto de TEST...")
model_act2.eval()
total_correctas_test = 0.0
total_muestras_test = 0.0

with torch.no_grad():
    for x, target in test_dl:
        x = x.cuda()
        target = target.cuda()
        output = model_act2(x)

        preds = output.argmax(dim=1)
        correctas = (preds == target).sum()
        total_correctas_test += correctas
        total_muestras_test += target.shape[0]

accuracy_test = total_correctas_test / total_muestras_test

# RESPUESTA:
print("\\n" + "="*60)
print("RESULTADOS ACTIVIDAD 2:")
print("="*60)
print(f"Train Accuracy final: {100*accuracy_train:.2f}%")
print(f"Test Accuracy: {100*accuracy_test:.2f}%")
print("\\nExplicación:")
print("El Dropout ayuda a prevenir el overfitting. Generalmente verás que:")
print("- El accuracy en TRAIN puede ser un poco más bajo que sin Dropout")
print("- El accuracy en TEST debería ser mejor o similar")
print("- La diferencia entre train y test debería ser menor")
print("Esto significa que el modelo generaliza mejor a datos nuevos.")
print("="*60)

Entrenando modelo CON Dropout por 10 épocas...
Época 1/10 - Train Accuracy: 2.51%
Época 2/10 - Train Accuracy: 4.13%
Época 3/10 - Train Accuracy: 5.86%
Época 4/10 - Train Accuracy: 7.10%
Época 5/10 - Train Accuracy: 8.84%
Época 6/10 - Train Accuracy: 11.61%
Época 7/10 - Train Accuracy: 13.35%
Época 8/10 - Train Accuracy: 15.60%
Época 9/10 - Train Accuracy: 17.57%
Época 10/10 - Train Accuracy: 21.08%
\n============================================================
¡Entrenamiento completado!
\nEvaluando en conjunto de TEST...
\n============================================================
RESULTADOS ACTIVIDAD 2:
Train Accuracy final: 21.08%
Test Accuracy: 23.01%
\nExplicación:
El Dropout ayuda a prevenir el overfitting. Generalmente verás que:
- El accuracy en TRAIN puede ser un poco más bajo que sin Dropout
- El accuracy en TEST debería ser mejor o similar
- La diferencia entre train y test debería ser menor
Esto significa que el modelo generaliza mejor a datos nuevos.


**Actividad 3**

In [51]:
# ACTIVIDAD 3: Agregar Batch Normalization antes de Conv3, Conv4 y Conv5
# ==========================================================================
# Batch Normalization normaliza los datos entre capas
# Esto ayuda a que el entrenamiento sea más estable y rápido

# Creamos una nueva versión del modelo CON BatchNorm
class MiAlexNetConBatchNorm(nn.Module):
    def __init__(self):
        super(MiAlexNetConBatchNorm, self).__init__()

        # Conv1 y Conv2 sin cambios
        self.conv1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels=96, kernel_size=(11,11), stride=(4,4), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        self.conv2 = nn.Sequential(
            nn.Conv2d(in_channels=96, out_channels=256, kernel_size=(5,5), stride=(1,1), padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )

        # AQUÍ ESTÁN LOS CAMBIOS: Agregamos BatchNorm2d ANTES de Conv3, Conv4 y Conv5
        # BatchNorm2d(256) normaliza los 256 canales que vienen de Conv2
        self.bn3 = nn.BatchNorm2d(256)  # ← NUEVO: BatchNorm antes de Conv3
        self.conv3 = nn.Sequential(
            nn.Conv2d(in_channels=256, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )

        # BatchNorm2d(384) normaliza los 384 canales que vienen de Conv3
        self.bn4 = nn.BatchNorm2d(384)  # ← NUEVO: BatchNorm antes de Conv4
        self.conv4 = nn.Sequential(
            nn.Conv2d(in_channels=384, out_channels=384, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.ReLU()
        )

        # BatchNorm2d(384) normaliza los 384 canales que vienen de Conv4
        self.bn5 = nn.BatchNorm2d(384)  # ← NUEVO: BatchNorm antes de Conv5
        self.conv5 = nn.Sequential(
            nn.Conv2d(in_channels=384, out_channels=256, kernel_size=(3,3), stride=(1,1), padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )

        self.flat = nn.Flatten()

        # Capas fully connected sin cambios
        self.fc6 = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(9216, 4096),
            nn.ReLU()
        )
        self.fc7 = nn.Sequential(
            nn.Dropout(0.5),
            nn.Linear(4096, 4096),
            nn.ReLU()
        )
        self.fc8 = nn.Sequential(
            nn.Linear(4096, 102)
        )

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        # Aplicamos BatchNorm ANTES de cada convolución
        x = self.bn3(x)  # ← Normalizamos antes de Conv3
        x = self.conv3(x)
        x = self.bn4(x)  # ← Normalizamos antes de Conv4
        x = self.conv4(x)
        x = self.bn5(x)  # ← Normalizamos antes de Conv5
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)
        return x

# Creamos y entrenamos el nuevo modelo
model_act3 = MiAlexNetConBatchNorm()
model_act3 = model_act3.cuda()

# Preparamos los datos
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)
test_dl = DataLoader(ds_test, batch_size=128)

n_epochs = 10
optimizer = Adam(model_act3.parameters(), lr=0.001)
loss_function = CrossEntropyLoss()

# ===== ENTRENAMIENTO CON BATCH NORMALIZATION =====
print("Entrenando modelo CON Batch Normalization por 10 épocas...")
print("="*60)

model_act3.train()
for epoch in range(1, n_epochs + 1):
    total_correctas = 0.0
    total_muestras = 0.0

    for x, target in train_dl:
        x = x.cuda()
        target = target.cuda()
        output = model_act3(x)
        loss = loss_function(output, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        preds = output.argmax(dim=1)
        correctas = (preds == target).sum()
        total_correctas += correctas
        total_muestras += target.shape[0]

    accuracy_train = total_correctas / total_muestras
    print(f"Época {epoch}/{n_epochs} - Train Accuracy: {100*accuracy_train:.2f}%")

print("\\n" + "="*60)
print("¡Entrenamiento completado!")
print("="*60)

# ===== EVALUACIÓN EN TEST =====
print("\\nEvaluando en conjunto de TEST...")
model_act3.eval()
total_correctas_test = 0.0
total_muestras_test = 0.0

with torch.no_grad():
    for x, target in test_dl:
        x = x.cuda()
        target = target.cuda()
        output = model_act3(x)

        preds = output.argmax(dim=1)
        correctas = (preds == target).sum()
        total_correctas_test += correctas
        total_muestras_test += target.shape[0]

accuracy_test = total_correctas_test / total_muestras_test

# RESPUESTA:
print("\\n" + "="*60)
print("RESULTADOS ACTIVIDAD 3:")
print("="*60)
print(f"Train Accuracy final: {100*accuracy_train:.2f}%")
print(f"Test Accuracy: {100*accuracy_test:.2f}%")
print("\\nExplicación:")
print("Batch Normalization hace que el entrenamiento sea más estable.")
print("Beneficios que podrías notar:")
print("- El modelo aprende más rápido (las primeras épocas tienen mejor accuracy)")
print("- El entrenamiento es más estable (menos variación entre épocas)")
print("- Puede mejorar el accuracy final tanto en train como en test")
print("- Funciona como una forma suave de regularización")
print("="*60)

Entrenando modelo CON Batch Normalization por 10 épocas...
Época 1/10 - Train Accuracy: 4.31%
Época 2/10 - Train Accuracy: 8.26%
Época 3/10 - Train Accuracy: 10.16%
Época 4/10 - Train Accuracy: 12.08%
Época 5/10 - Train Accuracy: 14.01%
Época 6/10 - Train Accuracy: 16.85%
Época 7/10 - Train Accuracy: 17.90%
Época 8/10 - Train Accuracy: 20.43%
Época 9/10 - Train Accuracy: 23.40%
Época 10/10 - Train Accuracy: 24.58%
\n============================================================
¡Entrenamiento completado!
\nEvaluando en conjunto de TEST...
\n============================================================
RESULTADOS ACTIVIDAD 3:
Train Accuracy final: 24.58%
Test Accuracy: 25.32%
\nExplicación:
Batch Normalization hace que el entrenamiento sea más estable.
Beneficios que podrías notar:
- El modelo aprende más rápido (las primeras épocas tienen mejor accuracy)
- El entrenamiento es más estable (menos variación entre épocas)
- Puede mejorar el accuracy final tanto en train como en test
- Funcion

Actividad 4

In [52]:
# ACTIVIDAD 4: Usar AlexNet preentrenado en ImageNet
# =====================================================
# Un modelo preentrenado ya aprendió características útiles de imágenes
# Solo necesitamos ajustar la última capa para nuestro problema específico

from torchvision.models import alexnet

# Cargamos AlexNet YA ENTRENADO en ImageNet (millones de imágenes)
# weights='IMAGENET1K_V1' es la forma moderna de cargar pesos preentrenados
model_act4 = alexnet(weights='IMAGENET1K_V1')

# Congelamos las capas convolucionales (features)
# Esto significa que NO se van a modificar durante el entrenamiento
# ¿Por qué? Porque ya aprendieron a detectar características útiles (bordes, formas, etc.)
model_act4.features.requires_grad_(False)

# SOLO entrenamos la parte final (classifier)
# La modificamos para que tenga 102 salidas (nuestro número de clases de flores)
model_act4.classifier = nn.Sequential(
    nn.Dropout(),
    nn.Linear(256 * 6 * 6, 4096),
    nn.ReLU(inplace=True),
    nn.Dropout(),
    nn.Linear(4096, 4096),
    nn.ReLU(inplace=True),
    nn.Linear(4096, 102),  # ← 102 clases de flores (en lugar de las 1000 de ImageNet)
)

model_act4 = model_act4.cuda()

# Preparamos los datos
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)
test_dl = DataLoader(ds_test, batch_size=128)

n_epochs = 10
# Solo optimizamos los parámetros del classifier (las features están congeladas)
optimizer = Adam(model_act4.classifier.parameters(), lr=0.001)
loss_function = CrossEntropyLoss()

# ===== ENTRENAMIENTO CON MODELO PREENTRENADO =====
print("Entrenando AlexNet PREENTRENADO por 10 épocas...")
print("(Solo se entrenan las capas finales, las features están congeladas)")
print("="*60)

model_act4.train()
for epoch in range(1, n_epochs + 1):
    total_correctas = 0.0
    total_muestras = 0.0

    for x, target in train_dl:
        x = x.cuda()
        target = target.cuda()
        output = model_act4(x)
        loss = loss_function(output, target)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        preds = output.argmax(dim=1)
        correctas = (preds == target).sum()
        total_correctas += correctas
        total_muestras += target.shape[0]

    accuracy_train = total_correctas / total_muestras
    print(f"Época {epoch}/{n_epochs} - Train Accuracy: {100*accuracy_train:.2f}%")

print("\\n" + "="*60)
print("¡Entrenamiento completado!")
print("="*60)

# ===== EVALUACIÓN EN TEST =====
print("\\nEvaluando en conjunto de TEST...")
model_act4.eval()
total_correctas_test = 0.0
total_muestras_test = 0.0

with torch.no_grad():
    for x, target in test_dl:
        x = x.cuda()
        target = target.cuda()
        output = model_act4(x)

        preds = output.argmax(dim=1)
        correctas = (preds == target).sum()
        total_correctas_test += correctas
        total_muestras_test += target.shape[0]

accuracy_test = total_correctas_test / total_muestras_test

# RESPUESTA:
print("\\n" + "="*60)
print("RESULTADOS ACTIVIDAD 4:")
print("="*60)
print(f"Train Accuracy final: {100*accuracy_train:.2f}%")
print(f"Test Accuracy: {100*accuracy_test:.2f}%")
print("\\nExplicación:")
print("El modelo preentrenado debería dar MUCHO MEJOR rendimiento porque:")
print("1. Ya sabe reconocer características básicas de imágenes")
print("   (bordes, texturas, formas) aprendidas de millones de imágenes")
print("2. Solo necesitamos entrenar la capa final para clasificar flores")
print("3. Esto es especialmente útil cuando tenemos pocos datos de entrenamiento")
print("\\nEsto se llama 'Transfer Learning' (aprendizaje por transferencia):")
print("Transferimos el conocimiento de un problema (ImageNet) a otro (flores)")
print("\\nEspera ver accuracy de TEST mucho más alto (probablemente 70-90%)")
print("comparado con entrenar desde cero (30-60%)")
print("="*60)

Entrenando AlexNet PREENTRENADO por 10 épocas...
(Solo se entrenan las capas finales, las features están congeladas)
Época 1/10 - Train Accuracy: 25.06%
Época 2/10 - Train Accuracy: 57.71%
Época 3/10 - Train Accuracy: 69.16%
Época 4/10 - Train Accuracy: 74.63%
Época 5/10 - Train Accuracy: 78.79%
Época 6/10 - Train Accuracy: 81.80%
Época 7/10 - Train Accuracy: 83.61%
Época 8/10 - Train Accuracy: 85.37%
Época 9/10 - Train Accuracy: 87.23%
Época 10/10 - Train Accuracy: 88.22%
\n============================================================
¡Entrenamiento completado!
\nEvaluando en conjunto de TEST...
\n============================================================
RESULTADOS ACTIVIDAD 4:
Train Accuracy final: 88.22%
Test Accuracy: 79.92%
\nExplicación:
El modelo preentrenado debería dar MUCHO MEJOR rendimiento porque:
1. Ya sabe reconocer características básicas de imágenes
   (bordes, texturas, formas) aprendidas de millones de imágenes
2. Solo necesitamos entrenar la capa final para clasifi